// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxPlxp1mfIlnc3xtKxtrT3cYILj0oNuVs',
    appId: '1:536550012612:web:5f4dbd2723b0059c9ebb91',
    messagingSenderId: '536550012612',
    projectId: 'qataar-f48c7',
    authDomain: 'qataar-f48c7.firebaseapp.com',
    storageBucket: 'qataar-f48c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbsZLI9shAI1nWcm0ew0rXyq6itKjDUo',
    appId: '1:536550012612:android:99f23eb523095caf9ebb91',
    messagingSenderId: '536550012612',
    projectId: 'qataar-f48c7',
    storageBucket: 'qataar-f48c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy9RimO4HwDvJmRAN6HZirraH8hpLGAVM',
    appId: '1:536550012612:ios:1afdd5c946c337609ebb91',
    messagingSenderId: '536550012612',
    projectId: 'qataar-f48c7',
    storageBucket: 'qataar-f48c7.firebasestorage.app',
    iosBundleId: 'com.example.qataar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxPlxp1mfIlnc3xtKxtrT3cYILj0oNuVs',
    appId: '1:536550012612:web:da981c9bb80203e49ebb91',
    messagingSenderId: '536550012612',
    projectId: 'qataar-f48c7',
    authDomain: 'qataar-f48c7.firebaseapp.com',
    storageBucket: 'qataar-f48c7.firebasestorage.app',
  );
}
